# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Derong Jin
name: Derong Jin
name_cn: 金德容
position: Master's Student
email: djin77@umd.edu
description: >-
  I am a first year Master's student in [Computer Science](https://www.cs.umd.edu/) at [University of Maryland, College Park](https://umd.edu/), advised by [Prof. Ruohan Gao](https://www.cs.umd.edu/people/rhgao). 

  My research interests lie in the intersection of <b>computer vision and machine learning</b>, with a focus on <b>multi-modal 3D reconstruction</b>. 

  <br/>

  I received my B.Eng. in Computer Science and Engineering from [The Chinese University of Hong Kong, Shenzhen](https://www.cuhk.edu.cn/en/) in 2024, where I was advised by [Prof. Xiaoguang Han](https://gaplab.cuhk.edu.cn/pages/people).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://HuMathe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DerongJin
github_username: HuMathe
google_scholar: p6UM7skAAAAJ
google_analytics: GTM-WJ8X46LN

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact


# I am a researcher in 3D computer vision and generative AI. I currently co-lead the development of spatial intelligence at [World Labs](https://www.worldlabs.ai/blog).
# I was previously a research scientist at [Google](https://ai.google/research/) where I built technology to [generate 3D assets](https://blog.google/products/shopping/search-on-2022-shopping/) for products on Google Search.

# I received my Ph.D from the [University of Washington](https://grail.cs.washington.edu/) in 2021 where I was advised by
# [Ali Farhadi](https://homes.cs.washington.edu/~ali/) and
# [Steve Seitz](https://homes.cs.washington.edu/~seitz/).

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
